name: tdd_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^6.1.0
  uuid: ^4.1.0
  # Date Formatting
  intl: ^0.18.1
  # Audio Record
  record: ^4.4.4
  audioplayers: ^5.2.0
  permission_handler: ^11.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
