name: tdd_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6

  # State Management
  get: 4.6.6

  # Fonts
  google_fonts: ^6.1.0
  uuid: ^4.2.1

  # Date Formatting
  intl: ^0.18.1

  # Audio Record
  record: ^5.0.1
  audioplayers: ^5.2.0
  permission_handler: ^11.0.1

  # Local Data Store
  shared_preferences: ^2.2.2

  # Pusher Channel
  pusher_channels_flutter: ^2.2.0

  # HTTP Calls
  http: ^1.1.0
  pretty_http_logger: ^1.0.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
